/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Variant = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
});
export const Category = IDL.Text;
export const ProductInput = IDL.Record({
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(Variant),
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(Variant),
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'variant' : Variant,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'orderId' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [ProductId], []),
  'addToCart' : IDL.Func([ProductId, Variant, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ProductId, Variant, IDL.Nat))],
      ['query'],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([ProductId, Variant], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartItem' : IDL.Func([ProductId, Variant, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Variant = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
  });
  const Category = IDL.Text;
  const ProductInput = IDL.Record({
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(Variant),
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(Variant),
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'variant' : Variant,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'orderId' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [ProductId], []),
    'addToCart' : IDL.Func([ProductId, Variant, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ProductId, Variant, IDL.Nat))],
        ['query'],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([ProductId, Variant], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartItem' : IDL.Func([ProductId, Variant, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };