/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface Order {
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : Principal,
  'orderId' : bigint,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'variant' : Variant,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : ProductId,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'variants' : Array<Variant>,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ProductInput {
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'variants' : Array<Variant>,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Variant { 'color' : [] | [string], 'size' : [] | [string] }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], ProductId>,
  'addToCart' : ActorMethod<[ProductId, Variant, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<[ProductId, Variant, bigint]>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string], bigint>,
  'removeFromCart' : ActorMethod<[ProductId, Variant], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartItem' : ActorMethod<[ProductId, Variant, bigint], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];